### ISSUE TITLE
Offline Deck Testing

### ISSUE THREAD

**Issue by crazy-crab-lord** [JollyGrin/unbrewed-p2p#25]
I love the new update but it would also be great to have back the offline testing where it was just the deck and nothing else. Me and some friends used it to play with characters on a physical board.

**Comment by JollyGrin** [comment]
@crazy-crab-lord Ah this is great to know!

Will prioritise this! Thanks for bringing this up

**Comment by JollyGrin** [comment]
@crazy-crab-lord Just made a SUPER mvp version for the offline mode. Can join via the /connect screen and it will load your starred deck

![Image](https://github.com/JollyGrin/unbrewed-p2p/assets/28109194/a4a1c3b3-b7fc-465f-b9cb-8c7112925616)


In the future I'll clean this up, but I wanted it to at least work on mobile first and get it working quickly.

Todo: 
- saving: right now when you refresh the page it will completely reset
- styling: just pasted the text for hero/sidekick without any icons or styling

Let me know if you come across anything. I'll close if no further requests on this point

**Comment by JollyGrin** [comment]
@crazy-crab-lord closing this ticket now that the offline page works! Thank you for letting me know how you use unbrewed!

If you have further suggestions feel free to make a new ticket!
