### ISSUE TITLE
unbrewed Online Lobby Moving Tokens

### ISSUE THREAD

**Issue by CloverLier** [JollyGrin/unbrewed-p2p#41]
I am unable to move tokens in the online lobby but can offline. Was wondering if there is a way to fix this. Please help.

**Comment by JollyGrin** [comment]
@CloverLier I think this is a silly bug, when multiple players join the game, their tokens will be on the same location. 

If another person's token is covering your token, it might block your ability to move your own. 

Try having everyone click the token and try moving it. It's likely someone else's token was on top.

**Comment by JollyGrin** [comment]
Actually this is silly, note to self: fix by slightly randomizing where location of token is, so its easy to find yours without being blocked by another

OR: always have "your" token on top, no matter what. Opponents tokens always under yours.

**Comment by JollyGrin** [comment]
Fixed!
